### ISSUE TITLE
THT parts are not exported in CPL file; only SMT

### ISSUE THREAD

**Issue by laf0rge** [oxullo/jlcpcb-eagle#12]
JLCPCB supports soldering of THT parts.  However, the ULP here for generating the CPL file only exports SMT parts.   THT parts will be missing, even though LCSC/JLCPCB has them in the library and even though the LCSC_PART attributes are set for those THT parts.

**Comment by oxullo** [comment]
Hey @laf0rge 
THT parts should be added to the components list both for BOM and CPL, since the merge of the feature/tht branch. Have you used a recent rev for your test?
Can you share a sample brd file that verifies the issue?

**Comment by oxullo** [comment]
I'm closing this one, I imply that this is already fixed.

**Comment by laf0rge** [comment]
sorry for never providing feedback, guess I missed your update back [almost] one year ago. Thanks in any case!
