### ISSUE TITLE
Parts rotated extra 180º on bottom side

### ISSUE THREAD

**Issue by ideaalab** [oxullo/jlcpcb-eagle#13]
A component on the top side is correctly placed (rotated) in the JLCPCB assembly viewer, but rotated extra 180º if placed on the bottom side.
Eagle example PCB design
![image](https://github.com/oxullo/jlcpcb-eagle/assets/25922675/1cca4fac-8a1a-4b4e-9757-5e41d726006e)

Part placed:
![image](https://github.com/oxullo/jlcpcb-eagle/assets/25922675/c3816f7e-cda5-43e4-b556-2bc768c73128)

JLCPCB top placement:
![image](https://github.com/oxullo/jlcpcb-eagle/assets/25922675/2f3460a6-40a5-4818-bb64-bb31d370058f)

JLCPCB bottom placement:
![image](https://github.com/oxullo/jlcpcb-eagle/assets/25922675/91306e13-8baf-4661-953b-00c55aa1b8b3)

Production files (Gerbers, BOM and CPL)
[production_files.zip](https://github.com/oxullo/jlcpcb-eagle/files/13561103/production_files.zip)

Looks like bottom side components need to substract 180º from current rotation

**Comment by ideaalab** [comment]
Checking the Eagle properties from the components, both top and bottom has a rotation of 90º.
But exported CPL has 90º on top and 270º on bottom. So looks like the ULP is adding 180º at some place.

**Comment by ideaalab** [comment]
Yes, lines 149 to 151 of the ULP are the ones generating this problem.
Could this be fixed at master?

**Comment by oxullo** [comment]
Thanks for reporting it, @ideaalab 
I'm not sure if the behavior has been changed upstream, as far as I remember, this kludge was required for the mirrored parts.

**Comment by ideaalab** [comment]
Thanks for fixing this. Is likely that JLCPCB changed the way they process the CPL files.
