### ISSUE TITLE
A good method to collaborate with you

### ISSUE THREAD

**Issue by JLCPCB** [oxullo/jlcpcb-eagle#4]
Hi Oxullo,

Good day.

I'm Atommann from JLCPCB, I joined JLCPCB as a PCB layout engineer one week ago. One of my job is to update the tech tutorials and other tech related stuff in JLCPCB's website.

When I was thinking how to update the Eagle tutorial I searched around and see your cool project.

I just forked your repo, but I am wondering if there's a better way of collaboration.

https://github.com/JLCPCBofficial/jlcpcb-eagle

Thank you.

--
Atommann

**Comment by oxullo** [comment]
Hey @JLCPCB I'm closing this issue since we've already established a workflow
