### ISSUE TITLE
How to get Through Hole to pull through

### ISSUE THREAD

**Issue by tekadept** [oxullo/jlcpcb-eagle#6]
Just wondering how I get through hole components to be exported to BOM and CPL? is there a value I have to assign or something?

**Comment by oxullo** [comment]
Hey @tekadept, TH support should come somewhen soon, I'll keep this issue open until it'll happen.

**Comment by oxullo** [comment]
Hello @tekadept the feature is now on master, edd654916a86cdd5421dda70721ac8395e6bad9d. If you have the chance to test it, please let me know!
