### ISSUE TITLE
Bill of Material Error

### ISSUE THREAD

**Issue by warp929** [oxullo/jlcpcb-eagle#7]
Thank you for the ULP but I found and error when generating the bill of material.  I'm using Eagle 9.6.2 and just downloaded your ULP yesterday.  It works well for components that have "LCSC" defined but fails on components that don't.  Either no LCSC attribute or the LCSC attribute value is blank leads to that component being listed under Designator for another component.  

**For example:**
Designator
D209 D210 U105 U203 C101 C106 C107 C108   C110 C206 C208 C209 C211

You can see diodes and a RF-PCBA are being grouped with a capacitor that has an LCSC defined part number.  That is incorrect.

**Comment by oxullo** [comment]
Hello @warp929 commit 0940c0e7247deceb3182a519ab4c3f61612b0a4a might have addressed this issue, could you try again, please?

**Comment by oxullo** [comment]
Considering it fixed and closing the issue
