### ISSUE TITLE
Comp with same value and different footprint

### ISSUE THREAD

**Issue by Domodar** [oxullo/jlcpcb-eagle#8]
Hi
I've noticed that Comp with same value and different footprint are exported under one footprint.
ex:
C1 is 0603 100n
C2, C3 are 0402 100n
on bom I get
C1, C2, C3 0402 100n

Eagle 9.6.1

**Comment by daveindustries** [comment]
Firstly thanks for the script its saved me a ton of time, but had the same issue crop up where parts of the same value but different footprint get put together. 

in schematic:
F1, 500mA 0603
F2, 500mA 1206

BOM output would be:
F1,F2 500mA 1206

Fusion 360 v2.0.13162
macOS 12.3.1 x86_64 (21E258) on MacBookPro18,2

**Comment by oxullo** [comment]
The issue should be now addressed, please reopen otherwise!
